# NumPy Basics

##  Importing NumPy

NumPy is a Python library used for numerical and array operations.

In [2]:
import numpy as np

print("NumPy Imported Successfully")

NumPy Imported Successfully


In [3]:
numbers = np.array([1, 2, 3, 4, 5])

print(numbers)

[1 2 3 4 5]


##  Array Operations

NumPy allows fast mathematical operations on arrays.

In [4]:
print(numbers + 2)
print(numbers * 2)

[3 4 5 6 7]
[ 2  4  6  8 10]


##  Array Indexing

Indexing is used to access specific elements from an array.

In [5]:
print(numbers[0])
print(numbers[2])

1
3


##  Array Shape

The shape tells the dimensions of an array.

In [6]:
print(numbers.shape)

(5,)


##  Zeros Array

NumPy can create arrays filled with zeros.

In [7]:
zeros_array = np.zeros(5)

print(zeros_array)

[0. 0. 0. 0. 0.]


##  Ones Array

NumPy can create arrays filled with ones.

In [8]:
ones_array = np.ones(5)

print(ones_array)

[1. 1. 1. 1. 1.]


##  Random Arrays

NumPy can generate random numbers automatically.

In [9]:
random_array = np.random.randint(1, 10, 5)

print(random_array)

[9 7 7 2 9]


##  Linspace

Linspace creates evenly spaced numbers between a range.

In [10]:
line_array = np.linspace(0, 10, 5)

print(line_array)

[ 0.   2.5  5.   7.5 10. ]


##  2D Arrays

NumPy supports multi-dimensional arrays.

In [11]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [12]:
print(matrix[0][1])

2
