# NumPy Advanced

This notebook covers advanced NumPy concepts used in data analysis and scientific computing.

Topics Covered:
- Reshape Arrays
- Mathematical Operations
- Array Statistics

## 1. Reshape Arrays

Reshape is used to change the shape of an array without changing its data.

Why it is useful:
It helps organize data into rows and columns.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

## 2. Mathematical Operations

NumPy allows mathematical operations on arrays.

Examples:
- Addition
- Subtraction
- Multiplication
- Division

In [ ]:
import numpy as np

a = np.array([10, 20, 30])

b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


## 3. Array Statistics

NumPy provides built-in functions for calculations.

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


## Key Concepts Learned

- Reshaping Arrays using reshape()
- Mathematical Operations on Arrays
- Statistical Functions in NumPy
- Efficient Numerical Computing

## Summary

In this section, we learned:

✅ Reshape Arrays

✅ Mathematical Operations

✅ Array Statistics

✅ Basic Data Analysis using NumPy